### ISSUE TITLE
test-engine-live error in fsunlink in packager.js after 21 hours streaming to S3

### ISSUE THREAD

**Issue by mcshicks** [orcasound/orcanode#1]
We get an intermittent in test engine live where it try to unlink a null reference to a file.  Here is the log file

The packager has processed: /tmp/dash_output_dir/audio_1319.ts.mp4. Last run was 9370ms ago. Average time between runs: 14997.639878695985ms.
packager.js:25
TypeError: path must be a string or Buffer
fs.js:1107
    at TypeError (native)
    at Object.fs.unlink (fs.js:1107:11)
    at /root/test-engine-live-tools/lib/packager.js:30:10
    at Array.forEach (native)
    at /root/test-engine-live-tools/lib/packager.js:29:96
    at ChildProcess.<anonymous> (/root/test-engine-live-tools/lib/packager.js:57:80)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)

This issue actually has happened on udoo and raspberry pi nodes as in two different locations.

Reproduction - on raspberry pi using armv32 branch commit commit 94285113a8d622a6a5658c42ec71eb3b98751c4c  with appropriate .env file do docker-compose up to start streaming to AWS.  After approximately 21 hours you will get this error

**Comment by mcshicks** [comment]
Debug Screenshot
file:///home/steve/Pictures/DebugScreenshot.png

**Comment by mcshicks** [comment]
It seems like MP4Box had a segmentation fault.  Screen shot of debugger capture 
![image](https://user-images.githubusercontent.com/3165216/35305140-1dfdb55c-004d-11e8-86e1-19dd3e145962.png)

The input file was audio_584.ts and it was deleted on the container

-rw-r--r-- 1 root root 134984 Jan 22 20:09 audio_588.ts
-rw-r--r-- 1 root root 151340 Jan 22 20:09 audio_587.ts
-rw-r--r-- 1 root root 150024 Jan 22 20:09 audio_586.ts
-rw-r--r-- 1 root root 151340 Jan 22 20:09 audio_585.ts
root@229ad03ec990:/tmp/dash_segment_input_dir# ls -l -t
